In [304]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [305]:
data = pd.read_csv('car.data')
# print(data.head())
x = data[['buying','maint','safety']].values    # features (input variables)
y = data[['class']]     # labels (output variable)
print(x)
# print(y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]


In [306]:
# converting the categorical data into numeric data
# converting x using fit_transform
le = LabelEncoder()
print(len(x[0]))
for i in range(len(x[0])):
  x[:,i] = le.fit_transform(x[:,i])
print(x)

3
[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [307]:
# converting y using .map function
label_mapping = {'unacc': 0, 'acc': 1,'good':2,'vgood':3}
y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


C:\Users\Acer1\AppData\Local\Temp\ipykernel_5356\2598278305.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


In [308]:
# creating model
knn = neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
knn.fit(x_train,y_train)
prediction = knn.predict(x_test)
accuracy = metrics.accuracy_score(y_test,prediction)
print('Prediction: ',prediction)
print('Accuracy: ',accuracy*100, '%')
a = 150
print('Predicted value: ',knn.predict(x)[a])
print('Actual value: ',y[a])


Prediction:  [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 2 0 0 1 0 1 0 0 1 0
 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 2
 0 0 0 0 1 1 0 0 0 2 0 1 0 0 1 2 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 2 0 0
 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 0 1 0 0 0 0 0 0 2
 0 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 2 1 0 1 0 0 0 0 0 2 0 2 0 0 0 0 1 0 0
 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 1 0 1
 0 1 1 0 0 1 0 0 0 2 0 0 1 0 2 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 1 2 0
 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 1 0 0 0 0 2 0 1 1 0 2 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 1 1 0 0 0 1 1 0 0 0]
Accuracy:  72.83236994219652 %
Predicted value:  0
Actual value:  [0]


C:\Users\Acer1\AppData\Roaming\Python\Python312\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
